# Generated by Django 3.2 on 2023-06-01 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_again'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Подьзователи'},
        ),
    ]
