# Generated by Django 3.2 on 2023-05-21 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_start_and_made_user_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
