# Generated by Django 3.2 on 2023-05-29 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_subscribe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
    ]
