# Generated by Django 3.2 on 2023-06-01 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_follow_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ('-author_id',), 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-id',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Подьзователи'},
        ),
    ]
