# Generated by Django 3.2 on 2023-05-31 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_follow_check'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscription',
            new_name='Follow',
        ),
    ]
